export const RECIPE_PACKS = [
  {
    slug: "inbox-crm",
    title: "Inbox CRM",
    podName: "inbox-crm",
    description: "Inbox-native CRM with embedded Gmail, deal context, tasks, reminders, and AI sales workflows.",
    operatorLoop: "Sales operators triage inbound conversations, update deals, and move pipeline stages without leaving the desk.",
    primaryBlocks: [
      "lemma-records-view",
      "lemma-detail-panel",
      "lemma-global-search",
      "lemma-action-surface",
      "lemma-assistant-experience",
      "lemma-file-browser",
      "lemma-insights",
    ],
    routes: ["/issues", "/members", "/files", "/pages", "/insights", "/workflow", "/assistant"],
    resourceSummary: ["Existing live example pod", "Uses the canonical inbox CRM desk in examples/inbox-crm"],
    provision: false,
  },
  {
    slug: "issue-tracker",
    title: "Issue Tracker",
    podName: "recipe-issue-tracker",
    description: "Linear/Jira-style issue tracker for engineering and product delivery.",
    operatorLoop: "Operators scan the issue queue, prioritize work, update status, and hand context to an assistant when needed.",
    primaryBlocks: [
      "lemma-records-view",
      "lemma-detail-panel",
      "lemma-status-flow",
      "lemma-comments",
      "lemma-activity-feed",
      "lemma-assistant-experience",
    ],
    routes: ["/issues", "/issues/:recordId", "/assistant", "/reports"],
    resourceSummary: ["issues table", "issue-copilot assistant"],
    provision: true,
    folders: [{ path: "/specs", description: "Issue specs and design notes" }],
    tables: [
      {
        name: "issues",
        enable_rls: false,
        columns: [
          { name: "identifier", type: "TEXT", required: true, max_length: 32, unique: true },
          { name: "title", type: "TEXT", required: true, max_length: 255 },
          { name: "description", type: "TEXT" },
          { name: "status", type: "ENUM", required: true, default: "backlog", options: ["backlog", "todo", "in_progress", "in_review", "done"] },
          { name: "priority", type: "ENUM", required: true, default: "medium", options: ["urgent", "high", "medium", "low"] },
          { name: "team", type: "TEXT", max_length: 64 },
          { name: "assignee_user_id", type: "UUID" },
          { name: "reporter_user_id", type: "UUID" },
          { name: "target_date", type: "DATE" },
        ],
      },
    ],
    assistants: [
      {
        name: "issue-copilot",
        instruction: "Help engineering operators summarize issue context, draft next steps, and spot missing acceptance criteria using the issues table and specs folder.",
        accessible_tables: [{ table_name: "issues", mode: "WRITE" }],
        accessible_folders: ["/specs"],
      },
    ],
    seed: {
      issues: [
        {
          identifier: "ISS-101",
          title: "Search results hide recently updated issues",
          description: "Operators cannot find the newest issues when sorting by updated activity.",
          status: "in_progress",
          priority: "urgent",
          team: "Search",
          target_date: "2026-04-25",
        },
        {
          identifier: "ISS-102",
          title: "Status badges overflow in compact list rows",
          description: "Compact density truncates long enum labels in the primary queue.",
          status: "todo",
          priority: "high",
          team: "Frontend",
          target_date: "2026-04-28",
        },
        {
          identifier: "ISS-103",
          title: "Workflow handoff misses linked specs",
          description: "Issue detail needs direct links into the specs folder before release review.",
          status: "backlog",
          priority: "medium",
          team: "Platform",
          target_date: "2026-05-02",
        },
      ],
    },
  },
  {
    slug: "triage-inbox",
    title: "Triage Inbox",
    podName: "recipe-triage-inbox",
    description: "Shared intake queue for operations teams reviewing new work from multiple channels.",
    operatorLoop: "Operators scan new inbound items, classify urgency, assign owners, and convert the item into downstream work.",
    primaryBlocks: [
      "lemma-records-view",
      "lemma-detail-panel",
      "lemma-status-flow",
      "lemma-global-search",
      "lemma-action-surface",
      "lemma-insights",
    ],
    routes: ["/queue", "/queue/:recordId", "/assistant", "/insights"],
    resourceSummary: ["triage_items table", "triage-assistant assistant"],
    provision: true,
    folders: [{ path: "/intake-context", description: "Reference docs for triage decisions" }],
    tables: [
      {
        name: "triage_items",
        enable_rls: false,
        columns: [
          { name: "identifier", type: "TEXT", required: true, max_length: 32, unique: true },
          { name: "subject", type: "TEXT", required: true, max_length: 255 },
          { name: "summary", type: "TEXT" },
          { name: "source", type: "ENUM", required: true, default: "email", options: ["email", "slack", "form", "manual"] },
          { name: "status", type: "ENUM", required: true, default: "new", options: ["new", "reviewing", "escalated", "resolved"] },
          { name: "priority", type: "ENUM", required: true, default: "normal", options: ["urgent", "high", "normal", "low"] },
          { name: "owner_user_id", type: "UUID" },
          { name: "received_at", type: "DATETIME" },
        ],
      },
    ],
    assistants: [
      {
        name: "triage-assistant",
        instruction: "Help operators classify inbox items, draft concise summaries, and suggest the next team or workflow for each triage item.",
        accessible_tables: [{ table_name: "triage_items", mode: "WRITE" }],
        accessible_folders: ["/intake-context"],
      },
    ],
    seed: {
      triage_items: [
        {
          identifier: "TRI-201",
          subject: "Billing export failed for finance close",
          summary: "Finance could not download the month-end export and needs a same-day response.",
          source: "email",
          status: "new",
          priority: "urgent",
          received_at: "2026-04-20T09:15:00Z",
        },
        {
          identifier: "TRI-202",
          subject: "Slack request for workspace access review",
          summary: "Ops needs approval on a new contractor access request from Slack intake.",
          source: "slack",
          status: "reviewing",
          priority: "high",
          received_at: "2026-04-20T10:30:00Z",
        },
        {
          identifier: "TRI-203",
          subject: "Manual intake for docs migration cleanup",
          summary: "A documentation backlog item was added manually after the migration review.",
          source: "manual",
          status: "escalated",
          priority: "normal",
          received_at: "2026-04-19T14:45:00Z",
        },
      ],
    },
  },
  {
    slug: "approval-workflow",
    title: "Approval Workflow",
    podName: "recipe-approval-workflow",
    description: "Approval desk for purchase, legal, and policy reviews with a real workflow resource.",
    operatorLoop: "Reviewers inspect pending requests, record a decision, and track the workflow run tied to the approval action.",
    primaryBlocks: [
      "lemma-records-view",
      "lemma-detail-panel",
      "lemma-status-flow",
      "lemma-action-surface",
      "lemma-workflow-runner",
      "lemma-comments",
    ],
    routes: ["/approvals", "/approvals/:recordId", "/workflow"],
    resourceSummary: ["approval_requests table", "approval-decision workflow"],
    provision: true,
    folders: [{ path: "/approval-attachments", description: "Supporting files for approval requests" }],
    tables: [
      {
        name: "approval_requests",
        enable_rls: false,
        columns: [
          { name: "identifier", type: "TEXT", required: true, max_length: 32, unique: true },
          { name: "title", type: "TEXT", required: true, max_length: 255 },
          { name: "summary", type: "TEXT" },
          { name: "category", type: "ENUM", required: true, default: "purchase", options: ["purchase", "security", "legal", "finance"] },
          { name: "status", type: "ENUM", required: true, default: "submitted", options: ["submitted", "approved", "rejected", "needs_info"] },
          { name: "amount", type: "FLOAT" },
          { name: "requester_name", type: "TEXT", max_length: 128 },
          { name: "approver_user_id", type: "UUID" },
          { name: "due_date", type: "DATE" },
        ],
      },
    ],
    workflows: [
      {
        name: "approval-decision",
        description: "Capture an approval decision and hand the run back to the desk for follow-up.",
        create: {
          name: "approval-decision",
          description: "Capture an approval decision and hand the run back to the desk for follow-up.",
          start: { type: "MANUAL" },
        },
        graph: {
          start: { type: "MANUAL" },
          nodes: [
            {
              id: "collect_decision",
              type: "FORM",
              label: "Collect decision",
              config: {
                input_schema: {
                  type: "object",
                  properties: {
                    request_id: { type: "string" },
                    decision: { type: "string", enum: ["approve", "reject", "needs_info"] },
                    notes: { type: "string" },
                  },
                  required: ["request_id", "decision"],
                },
              },
            },
            {
              id: "finish",
              type: "END",
              label: "Done",
              config: {},
            },
          ],
          edges: [{ id: "edge_collect_finish", source: "collect_decision", target: "finish" }],
        },
      },
    ],
    seed: {
      approval_requests: [
        {
          identifier: "APR-301",
          title: "Approve annual observability contract",
          summary: "Engineering needs a renewal approved before the existing contract lapses.",
          category: "purchase",
          status: "submitted",
          amount: 24000,
          requester_name: "Avery Chen",
          due_date: "2026-04-24",
        },
        {
          identifier: "APR-302",
          title: "Review vendor security questionnaire",
          summary: "Security requested a decision on a vendor onboarding packet.",
          category: "security",
          status: "needs_info",
          amount: 0,
          requester_name: "Mina Patel",
          due_date: "2026-04-26",
        },
        {
          identifier: "APR-303",
          title: "Approve updated customer terms addendum",
          summary: "Legal needs a fast review of a redlined contract addendum.",
          category: "legal",
          status: "approved",
          amount: 0,
          requester_name: "Jordan Kim",
          due_date: "2026-04-22",
        },
      ],
    },
  },
  {
    slug: "docs-workspace-os",
    title: "Docs Workspace OS",
    podName: "recipe-docs-workspace-os",
    description: "Internal knowledge workspace combining page records, pod files, and assistant help.",
    operatorLoop: "Operators browse page trees, open pod-backed documents, and use an assistant to navigate internal knowledge quickly.",
    primaryBlocks: [
      "lemma-page-tree",
      "lemma-document-workspace",
      "lemma-file-browser",
      "lemma-breadcrumbs",
      "lemma-assistant-experience",
    ],
    routes: ["/pages", "/pages/:recordId", "/files", "/assistant"],
    resourceSummary: ["pages table", "workspace folders", "knowledge-guide assistant"],
    provision: true,
    folders: [
      { path: "/workspace", description: "Top-level workspace documents" },
      { path: "/workspace/policies", description: "Policy documents" },
      { path: "/workspace/playbooks", description: "Operational playbooks" },
    ],
    tables: [
      {
        name: "pages",
        enable_rls: false,
        columns: [
          { name: "title", type: "TEXT", required: true, max_length: 255 },
          { name: "slug", type: "TEXT", required: true, max_length: 128, unique: true },
          { name: "summary", type: "TEXT" },
          { name: "status", type: "ENUM", required: true, default: "draft", options: ["draft", "in_review", "published", "archived"] },
          { name: "parent_page_id", type: "UUID" },
          { name: "file_path", type: "TEXT", max_length: 512 },
          { name: "owner_user_id", type: "UUID" },
        ],
      },
    ],
    assistants: [
      {
        name: "knowledge-guide",
        instruction: "Help operators find the right internal page or file quickly, summarize workspace content, and suggest missing documentation links.",
        accessible_tables: [{ table_name: "pages", mode: "WRITE" }],
        accessible_folders: ["/workspace", "/workspace/policies", "/workspace/playbooks"],
      },
    ],
    seed: {
      pages: [
        {
          title: "Workspace Home",
          slug: "workspace-home",
          summary: "Entry point for the internal docs workspace with links into policies and playbooks.",
          status: "published",
          file_path: "/workspace/home.lemma-doc.json",
        },
        {
          title: "Incident Response Policy",
          slug: "incident-response-policy",
          summary: "Policy covering severity levels, escalation, and communications.",
          status: "in_review",
          file_path: "/workspace/policies/incident-response.lemma-doc.json",
        },
        {
          title: "Customer Launch Playbook",
          slug: "customer-launch-playbook",
          summary: "Operational checklist for launching enterprise customers.",
          status: "draft",
          file_path: "/workspace/playbooks/customer-launch.lemma-doc.json",
        },
      ],
    },
  },
  {
    slug: "notion-copy",
    title: "Notion Copy",
    podName: "recipe-notion-copy",
    description: "Notion-style connected workspace with wiki pages, a lightweight database, files, search, and an AI guide.",
    operatorLoop: "Operators move between structured docs and database-style task tracking, then use search and assistant help to navigate the workspace quickly.",
    primaryBlocks: [
      "lemma-page-tree",
      "lemma-document-workspace",
      "lemma-records-view",
      "lemma-global-search",
      "lemma-file-browser",
      "lemma-assistant-experience",
      "lemma-action-surface",
      "lemma-workflow-runner",
    ],
    routes: ["/wiki", "/database", "/files", "/assistant"],
    resourceSummary: ["pages table", "workspace_tasks table", "workspace folders", "notion-guide assistant", "page-publish-review workflow"],
    provision: true,
    folders: [
      { path: "/workspace", description: "Top-level workspace content" },
      { path: "/workspace/wiki", description: "Wiki documents and home pages" },
      { path: "/workspace/templates", description: "Reusable page templates" },
      { path: "/workspace/meeting-notes", description: "Team meeting notes" },
    ],
    tables: [
      {
        name: "pages",
        enable_rls: false,
        columns: [
          { name: "title", type: "TEXT", required: true, max_length: 255 },
          { name: "slug", type: "TEXT", required: true, max_length: 128, unique: true },
          { name: "icon", type: "TEXT", max_length: 32 },
          { name: "page_type", type: "ENUM", required: true, default: "page", options: ["page", "database", "template", "meeting"] },
          { name: "status", type: "ENUM", required: true, default: "draft", options: ["draft", "in_review", "published", "archived"] },
          { name: "parent_page_id", type: "UUID" },
          { name: "file_path", type: "TEXT", max_length: 512 },
          { name: "owner_user_id", type: "UUID" },
        ],
      },
      {
        name: "workspace_tasks",
        enable_rls: false,
        columns: [
          { name: "identifier", type: "TEXT", required: true, max_length: 32, unique: true },
          { name: "title", type: "TEXT", required: true, max_length: 255 },
          { name: "status", type: "ENUM", required: true, default: "backlog", options: ["backlog", "next_up", "in_progress", "blocked", "done"] },
          { name: "priority", type: "ENUM", required: true, default: "medium", options: ["urgent", "high", "medium", "low"] },
          { name: "database_name", type: "TEXT", max_length: 128 },
          { name: "page_slug", type: "TEXT", max_length: 128 },
          { name: "assignee_user_id", type: "UUID" },
          { name: "due_date", type: "DATE" },
        ],
      },
    ],
    assistants: [
      {
        name: "notion-guide",
        instruction: "Help workspace operators find the right page, summarize wiki content, search the database-style task tables, and ask for confirmation before launching any publish workflow.",
        accessible_tables: [
          { table_name: "pages", mode: "WRITE" },
          { table_name: "workspace_tasks", mode: "WRITE" },
        ],
        accessible_folders: ["/workspace", "/workspace/wiki", "/workspace/templates", "/workspace/meeting-notes"],
      },
    ],
    agents: [
      {
        name: "workspace-librarian",
        description: "Background workspace analyst for summarizing and organizing docs knowledge.",
        instruction: "Summarize the requested workspace page or planning question using granted tables and folders. Return strict JSON with summary, recommended_updates, and open_questions. Do not persist durable business records.",
        input_schema: {
          type: "object",
          properties: {
            page_slug: { type: "string" },
            question: { type: "string" },
          },
          required: ["question"],
        },
        output_schema: {
          type: "object",
          properties: {
            summary: { type: "string" },
            recommended_updates: {
              type: "array",
              items: { type: "string" },
            },
            open_questions: {
              type: "array",
              items: { type: "string" },
            },
          },
          required: ["summary", "recommended_updates", "open_questions"],
        },
        tool_sets: ["SKILLS", "WORKSPACE_CLI", "FILE_SYSTEM"],
        accessible_tables: [
          { table_name: "pages", mode: "READ" },
          { table_name: "workspace_tasks", mode: "READ" },
        ],
        accessible_folders: ["/workspace", "/workspace/wiki", "/workspace/templates", "/workspace/meeting-notes"],
        accessible_applications: [],
      },
    ],
    workflows: [
      {
        name: "page-publish-review",
        description: "Collect a page publish decision and hand it back to the desk.",
        create: {
          name: "page-publish-review",
          description: "Collect a page publish decision and hand it back to the desk.",
          start: { type: "MANUAL" },
        },
        graph: {
          start: { type: "MANUAL" },
          nodes: [
            {
              id: "collect_publish_decision",
              type: "FORM",
              label: "Collect publish decision",
              config: {
                input_schema: {
                  type: "object",
                  properties: {
                    page_slug: { type: "string" },
                    decision: { type: "string", enum: ["publish", "request_changes", "archive"] },
                    notes: { type: "string" },
                  },
                  required: ["page_slug", "decision"],
                },
              },
            },
            {
              id: "finish",
              type: "END",
              label: "Done",
              config: {},
            },
          ],
          edges: [
            {
              id: "edge_collect_finish",
              source: "collect_publish_decision",
              target: "finish",
            },
          ],
        },
      },
    ],
    seed: {
      pages: [
        {
          title: "Company Home",
          slug: "company-home",
          icon: "home",
          page_type: "page",
          status: "published",
          file_path: "/workspace/wiki/company-home.lemma-doc.json",
        },
        {
          title: "Product Specs",
          slug: "product-specs",
          icon: "book",
          page_type: "database",
          status: "published",
          file_path: "/workspace/wiki/product-specs.lemma-doc.json",
        },
        {
          title: "Weekly Staff Notes",
          slug: "weekly-staff-notes",
          icon: "calendar",
          page_type: "meeting",
          status: "in_review",
          file_path: "/workspace/meeting-notes/weekly-staff.lemma-doc.json",
        },
      ],
      workspace_tasks: [
        {
          identifier: "DB-401",
          title: "Refresh onboarding checklist database",
          status: "in_progress",
          priority: "high",
          database_name: "Operations",
          page_slug: "company-home",
          due_date: "2026-04-24",
        },
        {
          identifier: "DB-402",
          title: "Review handbook template for new sections",
          status: "next_up",
          priority: "medium",
          database_name: "Wiki",
          page_slug: "product-specs",
          due_date: "2026-04-27",
        },
        {
          identifier: "DB-403",
          title: "Publish meeting note archive policy",
          status: "blocked",
          priority: "urgent",
          database_name: "Knowledge Ops",
          page_slug: "weekly-staff-notes",
          due_date: "2026-04-22",
        },
      ],
    },
  },
  {
    slug: "linear-copy",
    title: "Linear Copy",
    podName: "recipe-linear-copy",
    description: "Linear-style product delivery workspace with issues, projects, cycles, roadmaps, search, and an AI copilot.",
    operatorLoop: "Product and engineering operators scan issues, inspect project and cycle context, plan work, and use a workflow-backed planning flow when a new cycle starts.",
    primaryBlocks: [
      "lemma-records-view",
      "lemma-global-search",
      "lemma-insights",
      "lemma-file-browser",
      "lemma-assistant-experience",
      "lemma-action-surface",
      "lemma-workflow-runner",
    ],
    routes: ["/issues", "/projects", "/cycles", "/assistant", "/roadmap"],
    resourceSummary: ["issues table", "projects table", "cycles table", "linear-pm assistant", "cycle-planning workflow"],
    provision: true,
    folders: [
      { path: "/roadmaps", description: "Quarterly roadmap docs" },
      { path: "/cycles", description: "Cycle briefs and planning notes" },
      { path: "/project-briefs", description: "Project and initiative briefs" },
    ],
    tables: [
      {
        name: "projects",
        enable_rls: false,
        columns: [
          { name: "name", type: "TEXT", required: true, max_length: 255 },
          { name: "slug", type: "TEXT", required: true, max_length: 128, unique: true },
          { name: "summary", type: "TEXT" },
          { name: "status", type: "ENUM", required: true, default: "planned", options: ["planned", "active", "completed"] },
          { name: "lead_user_id", type: "UUID" },
          { name: "target_date", type: "DATE" },
        ],
      },
      {
        name: "cycles",
        enable_rls: false,
        columns: [
          { name: "name", type: "TEXT", required: true, max_length: 128, unique: true },
          { name: "cycle_number", type: "INTEGER", required: true },
          { name: "status", type: "ENUM", required: true, default: "planned", options: ["planned", "active", "completed"] },
          { name: "goal", type: "TEXT" },
          { name: "starts_on", type: "DATE" },
          { name: "ends_on", type: "DATE" },
        ],
      },
      {
        name: "issues",
        enable_rls: false,
        columns: [
          { name: "identifier", type: "TEXT", required: true, max_length: 32, unique: true },
          { name: "title", type: "TEXT", required: true, max_length: 255 },
          { name: "description", type: "TEXT" },
          { name: "status", type: "ENUM", required: true, default: "backlog", options: ["backlog", "todo", "in_progress", "in_review", "done"] },
          { name: "priority", type: "ENUM", required: true, default: "medium", options: ["urgent", "high", "medium", "low"] },
          { name: "team", type: "TEXT", max_length: 64 },
          { name: "project_slug", type: "TEXT", max_length: 128 },
          { name: "cycle_name", type: "TEXT", max_length: 128 },
          { name: "assignee_user_id", type: "UUID" },
          { name: "estimate", type: "INTEGER" },
        ],
      },
    ],
    assistants: [
      {
        name: "linear-pm",
        instruction: "Help product and engineering operators summarize delivery risk, connect issues to projects and cycles, and ask for confirmation before launching planning workflows.",
        accessible_tables: [
          { table_name: "projects", mode: "WRITE" },
          { table_name: "cycles", mode: "WRITE" },
          { table_name: "issues", mode: "WRITE" },
        ],
        accessible_folders: ["/roadmaps", "/cycles", "/project-briefs"],
      },
    ],
    agents: [
      {
        name: "delivery-researcher",
        description: "Background delivery analyst for planning and risk review.",
        instruction: "Review issues, projects, cycles, and roadmap files to answer delivery questions. Return strict JSON with summary, risks, and recommended_actions. Do not write durable business data.",
        input_schema: {
          type: "object",
          properties: {
            project_slug: { type: "string" },
            cycle_name: { type: "string" },
            question: { type: "string" },
          },
          required: ["question"],
        },
        output_schema: {
          type: "object",
          properties: {
            summary: { type: "string" },
            risks: {
              type: "array",
              items: { type: "string" },
            },
            recommended_actions: {
              type: "array",
              items: { type: "string" },
            },
          },
          required: ["summary", "risks", "recommended_actions"],
        },
        tool_sets: ["SKILLS", "WORKSPACE_CLI", "FILE_SYSTEM"],
        accessible_tables: [
          { table_name: "projects", mode: "READ" },
          { table_name: "cycles", mode: "READ" },
          { table_name: "issues", mode: "READ" },
        ],
        accessible_folders: ["/roadmaps", "/cycles", "/project-briefs"],
        accessible_applications: [],
      },
    ],
    workflows: [
      {
        name: "cycle-planning",
        description: "Collect planning inputs for a new cycle and hand the run back to the desk.",
        create: {
          name: "cycle-planning",
          description: "Collect planning inputs for a new cycle and hand the run back to the desk.",
          start: { type: "MANUAL" },
        },
        graph: {
          start: { type: "MANUAL" },
          nodes: [
            {
              id: "collect_cycle_plan",
              type: "FORM",
              label: "Collect cycle plan",
              config: {
                input_schema: {
                  type: "object",
                  properties: {
                    cycle_name: { type: "string" },
                    focus: { type: "string" },
                    ship_date: { type: "string" },
                  },
                  required: ["cycle_name", "focus"],
                },
              },
            },
            {
              id: "finish",
              type: "END",
              label: "Done",
              config: {},
            },
          ],
          edges: [{ id: "edge_collect_finish", source: "collect_cycle_plan", target: "finish" }],
        },
      },
    ],
    seed: {
      projects: [
        {
          name: "Search Reliability",
          slug: "search-reliability",
          summary: "Reduce noisy relevance regressions and make ranking changes safer to ship.",
          status: "active",
          target_date: "2026-05-10",
        },
        {
          name: "Desktop Expansion",
          slug: "desktop-expansion",
          summary: "Ship the next desk recipes and operator-quality improvements across the SDK examples.",
          status: "planned",
          target_date: "2026-05-24",
        },
      ],
      cycles: [
        {
          name: "Cycle 18",
          cycle_number: 18,
          status: "active",
          goal: "Stabilize workspace search and unblock the release train.",
          starts_on: "2026-04-15",
          ends_on: "2026-04-29",
        },
        {
          name: "Cycle 19",
          cycle_number: 19,
          status: "planned",
          goal: "Land the first end-to-end recipe expansion for docs and planning.",
          starts_on: "2026-04-30",
          ends_on: "2026-05-14",
        },
      ],
      issues: [
        {
          identifier: "LIN-501",
          title: "Issue detail misses cycle context when opened from search",
          description: "Operators lose the active cycle signal after jumping from global search into the issue sheet.",
          status: "in_progress",
          priority: "urgent",
          team: "Frontend",
          project_slug: "search-reliability",
          cycle_name: "Cycle 18",
          estimate: 5,
        },
        {
          identifier: "LIN-502",
          title: "Roadmap briefs are not visible from the project view",
          description: "PMs need direct access to brief files while reviewing project status changes.",
          status: "todo",
          priority: "high",
          team: "Product",
          project_slug: "desktop-expansion",
          cycle_name: "Cycle 19",
          estimate: 3,
        },
        {
          identifier: "LIN-503",
          title: "Planning workflow should capture shipping focus for the next cycle",
          description: "The cycle planning run needs a tighter handoff into the roadmap review cadence.",
          status: "backlog",
          priority: "medium",
          team: "Platform",
          project_slug: "desktop-expansion",
          cycle_name: "Cycle 19",
          estimate: 2,
        },
      ],
    },
  },
];

export function recipePackBySlug(slug) {
  return RECIPE_PACKS.find((recipe) => recipe.slug === slug) ?? null;
}
